server {
    listen 80;
    server_name _;

    client_max_body_size 20m;

    location / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param PATH_INFO "";
        fastcgi_pass app:9000;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
